### ISSUE TITLE
vlingo-e2e-sys-airline-ops issues

### ISSUE THREAD

**Issue by abdullahcalisir12** [vlingo/vlingo-examples#100]
1 -> After creating a fleet crew and then calling list of fleet crew endpoint returns me array of empty objects
2 -> I need an endpoint for monitoring page to show list of airplanes needs to be monitored
3 -> At air traffic control page after updating status of one then if you refresh the page you will see tail number and equipment updated data is undefined

**Comment by danilo-ambrosio** [comment]
Thanks for describing the details @abdullahcalisir12 

I'm working on this right now

**Comment by danilo-ambrosio** [comment]
@abdullahcalisir12 
1 and 3 are fixed. If you want to test it, please follow these steps:

1. `docker-compose stop`
2. `docker-compose rm`
3. `docker-compose up -d`
4. `git pull`
5. `mvn clean package`
6. `java -jar [service-folder]\target\[jar-name].jar [port-number]`

Regarding item 2, how many aircraft fields are needed? Is the aircraft id sufficient?

**Comment by abdullahcalisir12** [comment]
Thanks @danilo-ambrosio , for the item 2, @VaughnVernon wants this => `- Aircraft Monitoring: Tracks aircraft and provides information about the status of flights. This may be used for several purposes such as airlines and shipping analytics and airlines and airport information services.` So I'm not sure how to get the right data.

**Comment by VaughnVernon** [comment]
Let's not worry about that level of detail. It's only for hypothetical discussion. We won't actually build this out. Please wrap up the basic use cases that the REST already supports. We have bigger fish to fry. :)

**Comment by xiaoheiAh** [comment]
it'll print error message `io.vlingo.xoom.annotation.initializer.AddressFactory not exists` when i execute `mvn clean package`.
Is it be removed at xoom `1.5.1-SNAPSHOT`? Or may be covered?

**Comment by VaughnVernon** [comment]
@danilo-ambrosio Please provide an answer to @xiaoheiAh. I have checked and that class is indeed missing. Does the example need to be updated to a new version of vlingo-xoom? If this is a problem, why did we cause a breaking change here?

**Comment by VaughnVernon** [comment]
@xiaoheiAh This has probably been removed because the XOOM runtime now supports LATTICE Grid by default, which means that the Grid uses its own `AddressFactory` that is grid-capable. Is the code you are building from a pre-existing project?

@danilo-ambrosio Do you know why the class is still referenced? I checked through the codegen and can't find any references to it. I assume this must be in @xiaoheiAh own source code, probably from a pre-generated XOOM Starter use.

**Comment by danilo-ambrosio** [comment]
@xiaoheiAh 
Indeed, this class no longer exists. Have you experienced this issue only on `vlingo-e2e-sys-airline-ops` or somewhere else? 
If the problem only happens on  `vlingo-e2e-sys-airline-ops`, please just git pull and run `mvn clean package`. 

Please let me know if everything's running fine. 

Thanks!

**Comment by xiaoheiAh** [comment]
@VaughnVernon @danilo-ambrosio  
Thanks for help.It worked when I pulled latest commits.
It's my fault. :joy: I cloned this repo last week and didn't keep updating.
