### ISSUE TITLE
vlingo-reactive-messaging-patterns module has compile failure

### ISSUE THREAD

**Issue by bwehrle** [vlingo/vlingo-examples#21]
The signature is not correct for the actors that implement the Subscriber interface in this example.  
[ERROR] vlingo-examples/vlingo-reactive-messaging-patterns/src/main/java/io/vlingo/reactive/messaging/patterns/publishsubscribe/NYSESubscriber.java:[24,5] method does not override or implement a method from a supertype

**Comment by VaughnVernon** [comment]
Thanks @bwehrle we have released vlingo/platform v0.7.5 and everything should be sync'd now. If you can please confirm and close the issue. We still need some help with our Gradle build script that updates all dependencies by artifact version. The vlingo-examples repo has nested sub-projects that the build is not traversing to update those `pom.xml` and `README.md` files. See:

https://github.com/vlingo/vlingo-platform/blob/master/build.gradle

**Comment by bwehrle** [comment]
Hi @VaughnVernon ,
Ok, I think I understand now how you're managing the project deps dynamically.  This is not something that I've seen done before; typically this is managed via a BOM file from the platform project, which exports the latest versions.  These then are imported to the parent of the examples and then you're just changing the version of the import in one place.  I'll close this since this is the way you've designed the build process.
-Brian
