### ISSUE TITLE
vlingo-ecommerce fails with  Unknown event type: io.vlingo.examples.ecommerce.model.OrderEvents$Created

### ISSUE THREAD

**Issue by anderskristian** [vlingo/vlingo-examples#50]
I am trying to run 

mvn clean verify -pl vlingo-ecommerce

It ends with a lot of NPE

I just cannot make it work. I am also running the sample from Intellij - trying to contact the server started by io.vlingo.examples.ecommerce.Bootstrap
The result is similary .. process retry "endless" with NPE...

And I cannot really understand the sample. What should I expect from various things?
I made the ping-pong work ... 50% .. the no logging problem remains...

The learning curve seems high for me. I normally used to be able to follow tutorials - for vlingo - I still need the get the final clue..

Maybe it should be obvious for people .. certainly not for me

I just continue to having the feeling that you have not made all this without it is working...
/Anders

```
22:45:49.816 [pool-7-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=1, method=GET, uri=/cart/{cartId}, to=dynamic2(String cartId)
22:45:49.816 [pool-7-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=2, method=POST, uri=/cart, to=dynamic3()
22:45:49.816 [pool-7-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Resource: Order resource fluent api
22:45:49.816 [pool-7-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=0, method=POST, uri=/order/{orderId}/payment, to=dynamic1(String orderId)
22:45:49.816 [pool-7-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=1, method=GET, uri=/order/{orderId}, to=dynamic2(String orderId)
22:45:49.816 [pool-7-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=2, method=POST, uri=/order, to=dynamic3()
22:45:49.816 [pool-7-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Resource: User resource fluent api
22:45:49.817 [pool-7-thread-3] INFO  io.vlingo.actors.Logger - io.vlingo.http.resource.ServerActor - Action: id=0, method=GET, uri=/user/{userId}/cartSummary, to=dynamic1(Integer userId)
22:45:49.925 [pool-7-thread-4] DEBUG io.vlingo.actors.Logger - io.vlingo.symbio.store.journal.inmemory.InMemoryJournalActor - io.vlingo.symbio.store.journal.inmemory.InMemoryStreamReaderActor - Starting InMemoryStreamReaderActor named: OrderActor
22:45:49.926 [pool-7-thread-4] ERROR io.vlingo.actors.Logger - io.vlingo.actors.plugin.supervision.DefaultSupervisorOverride - DefaultSupervisorOverride: Failure of: Address[id=18, name=(none)] because: Unknown event type: io.vlingo.examples.ecommerce.model.OrderEvents$Created Action: Resuming.
java.lang.IllegalArgumentException: Unknown event type: io.vlingo.examples.ecommerce.model.OrderEvents$Created
	at io.vlingo.examples.ecommerce.infra.CartSummaryProjectionActor.createDataFromEvent(CartSummaryProjectionActor.java:62) ~[classes/:na]
	at io.vlingo.examples.ecommerce.infra.CartSummaryProjectionActor.projectWith(CartSummaryProjectionActor.java:75) ~[classes/:na]
	at io.vlingo.lattice.model.projection.Projection__Proxy.lambda$projectWith$cbd46963$1(Projection__Proxy.java:30) ~[vlingo-lattice-1.2.1.jar:na]
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121) ~[vlingo-actors-1.2.1.jar:na]
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53) ~[vlingo-actors-1.2.1.jar:na]
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:101) ~[vlingo-actors-1.2.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]


```

**Comment by VaughnVernon** [comment]
Hi @anderskristian Thanks for trying out the platform. May I suggest that you don't first attempt to build the platform locally? You should instead use the Maven dependencies to pull down the jars that you need to run.

Hi @bwehrle Could you please help @anderskristian with the problems he's experiencing with the `vlingo-ecommerce` example? (Anders, Brian is the author of this example.)

Regarding the ping-pong example, the logging issue that you observe is a matter of the time needed for the `Pinger` and `Ponger` to message each other 10 times. If this completes prior to the `Logger` processing all its log messages, the World is terminated and all actors stopped. Since the `Logger` is an actor it has not had time to process all its messages when the `World` is stopped. If you edit the `PingerActor` and `PongerActor` and replace the logger output with `System.out.println("...");` you will see that this is true. Perhaps this should be the default but we are attempting to show a realistic example of how actors should be used.

**Comment by anderskristian** [comment]
Okay, the ping/pong was a little frustration comment. I have made another example my self where logging works fine. But I cannot se the difference in the program and why the ping/pong should not work.

**Comment by VaughnVernon** [comment]
@anderskristian See this new commit to "fix" the problem.

3b1d36f...c45abb5

You may pull these updates into your local and retest.

**Comment by anderskristian** [comment]
Hi @VaughnVernon 

I an pretty sure I found the ping-pong logging problem

The situation is that **"self".stop()** and **"ponder".stop()** are executed before the logger has had a chance to write.
Yes - vlingo is fast :-)

Therefore code below - where I wait 20 ms after game over .. before stop actors works.

I am not designing vlingo - maybe stop() should consider flushing the logger.

At my current customer they might run crazy if a logging to ELK was missing.

We also got something called "I/O" logging where data going out of the company and coming in MUST be logged.  

So I am not sure I as a developer will expect a logging to be missing when I know that the thread had execured the code.

```
  @Override
  public void ping(final Ponger ponger) {
    ++count;
    logger().debug("ping " + count);
    if (count >= 10) {
      try {
        logger().debug("Game is ending");
        // we need to sleep a few milliseconds to let the logging actor complete
        // because we stop "self" actor right after the 10'th
        // iteration .. and the loop is so fast that logger gets not chance to
        // log.
        TimeUnit.MILLISECONDS.sleep(20);
      } catch (Exception e) {
        System.out.println("aborted");
      }
      self.stop();
      ponger.stop();
    } else {
      ponger.pong(self);
    }
  }

```

**Comment by VaughnVernon** [comment]
@anderskristian I understand your intentions but sleeping an actor thread is completely counter to the actor model. You are onto an idea, however. Perhaps during `World` termination each `Stage` can ensure that its `Logger` is flushed. That's possible using internal access to mailboxes.

**Comment by anderskristian** [comment]
Hi @VaughnVernon
1) I fully agree that sleep in an Actor is **against everything Actor stands for**.
2) I believe that self.stop() is a problem. 
     Putting the sleep before closing down the world does NOT solve the problem.

Below code WORKS !!!
```
  @Override
  public void ping(final Ponger ponger) {
    ++count;
    logger().debug("ping " + count);
    if (count >= 10) {
//      self.stop();
//      ponger.stop();
    } else {
      ponger.pong(self);
    }
  }
```

But the program never ends 

I have tried to remove self.stop() only - then ponger.stop() - both have to be removed to make logging printed

OK, **self.stop()** - removes logging ! - Question: Does it remove other business critical messages?

**Comment by anderskristian** [comment]
I have now debugged the ping/pung again

I can see that 
world.defaultlogger.mainbox.dispatcher.closed=false

During this period logging works !!!!!

When "self".stop() has been executed then

world.defaultlogger.mainbox.dispatcher.closed=true !!!!

And this is due to the **Actor.stop()** code

This code calls **lifecycle.stop(actor)**

```
  void stop(final Actor actor) {
    environment.stop();

    afterStop(actor);
  }

```

My impression is that **environment.stop()** is stopping too much !!!!
As I see it **dispatcher** is used by both the actor and the logger.

!!!!!!!!!!!!! I changed - remove environment.stop() !!!!!!!!!!!!!
Now ping/pong works

```
  void stop(final Actor actor) {
/////////    environment.stop();

    afterStop(actor);
  }

```

**Comment by VaughnVernon** [comment]
@anderskristian That's an excellent find! Thanks so much for your help! I have already fixed and pushed in the change to ConcurrentQueueMailbox.java in vlingo-actors.

**Comment by anderskristian** [comment]
This issue came to consider ping/pong sample - that was something completely different
I will close this issue - read a little more - and maybe open another issue
