### ISSUE TITLE
vlingo-platform-patterns fails with testThatChangingFileIsStable(io.vlingo.workoffload1.FileProcessorTest): expected:<Stable> but was:<null>

### ISSUE THREAD

**Issue by anderskristian** [vlingo/vlingo-examples#51]
The full build fails in the example package with described test

**Comment by VaughnVernon** [comment]
@anderskristian Thanks for the report. This is a known problem but does not reflect on the rest of the platform. It would be nice if you could take the time to look into this and fix it! 🥇

**Comment by anderskristian** [comment]
Okay I can try to see if I can understand the situation and fix it

**Comment by VaughnVernon** [comment]
@anderskristian See this new commit to "fix" the problem.

https://github.com/vlingo/vlingo-examples/compare/3b1d36f4ce64...c45abb52233d

You may pull these updates into your local and retest.

**Comment by VaughnVernon** [comment]
@anderskristian This is an example for a client that needed to check for file existence before processing the file. I don't recall all the details but it's basically an async document processing model. I don't know when/why exactly it stopped working.

**Comment by VaughnVernon** [comment]
This is working. Closed.
