### ISSUE TITLE
Maven dependency issues for inventory module

### ISSUE THREAD

**Issue by antoniocasino** [vlingo/vlingo-examples#99]
vlingo-build-plugins 1.5.1-snapshot dependency is not available.
io.vlingo.symbio.store.dispatch.Dispatcher is referenced in Bootstrap class but vlingo-symbio dependency is missing

**Comment by VaughnVernon** [comment]
@antoniocasino There were problems with Bintray and the snapshots for vlingo-build-plugins but not with snapshots on github packages. Are you sure you are referencing the correct dependencies?

/cc @jakzal

**Comment by jakzal** [comment]
@antoniocasino we migrated snapshots to GitHub packages, so if you haven’t set up authentication you might be getting old snapshots.

Please set up GitHub authentication in your maven settings like described here: 
https://github.com/vlingo/vlingo-examples#building-snapshots

**Comment by jakzal** [comment]
There's one more thing I noticed. Plugin repositories are not defined in our pom.xml. I'll fix that shortly.

**Comment by jakzal** [comment]
> There's one more thing I noticed. Plugin repositories are not defined in our pom.xml. I'll fix that shortly.

Should be fixed by https://github.com/vlingo/vlingo-examples/commit/6480fe6101545c11f845fa30370e245ffdba7103

@antoniocasino can you make sure your [GitHub authentication is set up](https://github.com/vlingo/vlingo-examples#building-snapshots) and try again please?

**Comment by antoniocasino** [comment]
Hi all,
I fixed my configuration with github as you suggested. I have noticed that
you use *dependency-reduced-pom.xml *instead of *pom.xml *for compilation,
and I didn't understand yet how this is configured.
During the build with *intellij idea* I add some errors regarding missed
dependencies.
Now I made a pull on vlingo-e2e-sys-airline-ops/inventory and the
compilation errors are gone. *Yee!*

A similar dependency issue is on http-front-service and http-back-service
I could successfully build those examples and run them on docker, but on
the IDE I still have missing deps warning.
I don't have much experience on docker so I am sorry if I make some newbie
mistakes.

**Comment by jakzal** [comment]
What I found helps IntelliJ is to Reload All Maven Projects. Press shift twice and start typing "reload all maven projects" until the option pops up, select it and press enter.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/190447/108606251-ed715d00-73b0-11eb-8daa-c55013c9832d.png">

IntelliJ should now fetch all dependencies in the background:

<img width="415" alt="image" src="https://user-images.githubusercontent.com/190447/108606279-1b56a180-73b1-11eb-99fa-2b6eef88fb46.png">

**Comment by antoniocasino** [comment]
Thanks, I'll check it out.

Il sab 20 feb 2021, 20:25 Jakub Zalas <notifications@github.com> ha scritto:

**Comment by jakzal** [comment]
We have now started publishing snapshots to [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/io/vlingo/) as well as GitHub. Sonatype is a more convenient option as it doesn't require authentication. 

To use it configure the Sonatype snapshots repository (and optionally the plugin repository) in your `pom.xml`:

```
<project>
  <!-- ... -->
  <repositories>
    <repository>
      <id>ossrh-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>ossrh-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
    </pluginRepository>
  </pluginRepositories>
</project>
```

Note that Sonatype will have snapshots starting with 1.5.3-SNAPSHOT (not the earlier ones).

I'm going to close the ticket as everything should be working fine again. Please let us know if you experienced further issues.
